### ISSUE TITLE
Audio file is added to queue but no transcription note is created

### ISSUE THREAD

**Issue by luketech85** [vincentbavitz/obsidian-vox#4]
When I add an audio file to the watch folder I get a notification that is has been added to the transcription queue.

However, it does not create a transcription note. IOW nothing seems to happen after that.

**Comment by anguschiu1** [comment]
I encounter the same issue as well. Originally I thought it is the problem about file format, but then I realise it seems to support .m4a file I am using, so perhaps there are other issues.

Is there any docs explaining how to self-hosting it? We can then eliminate some network issues during testing.

**Comment by stevenjetton** [comment]
I posted the same issue in "Discussion" before I saw this thread, so reposting here:

First, thank you Vincent for creating this free tool. I'm grateful for your generosity. I configured my personal settings, especially the watch file path and output file path. I added two audio files to my watch folder, one an .mp3 and the other a .mp4. I saw a notification alert confirming these two files were being added to the transcription queue, but, after waiting a while, i'm not seeing any transcriptions in my output folder, or error updates. Any thoughts on what I might be doing wrong?

**Comment by vincentbavitz** [comment]
Hey guys thanks for your comments - I really appreciate you documenting them. I'm going to investigate this today and get back to you on the status of this issue.

**Comment by vincentbavitz** [comment]
The incentive is strong to get this fixed because no one uses the plugin as much as I do!

**Comment by vincentbavitz** [comment]
Hey guys I found the issue; it's just a DNS issue to the backend server; I'll try to have this fixed on new year!

**Comment by vincentbavitz** [comment]
Please make sure you're on the latest version of the VOX plugin and everything should be working now guys. Many thanks!

**Comment by stevenjetton** [comment]
@vincentbavitz Thanks for working on this. Congrats! You got it working and it seems to be working really well as far as the actual transcription. However, there are a couple of new issues:

1. I had four audio files get added to the queue.
2. The plugin did it's job!
3. However, the plugin keeps looping thru the same audio files and creating duplicates of the same audio file, on an endless loop. Screen shot attached
4. The audio files get copied and saved in a newly created folder by the plugin and in the transcribed file. For example, My target folder is /transcription. A new folder called "/audio" got created here "/transcrtiption/audio/" and the loop keeps dumping a copy of the original audio files I added to my watch folder, endlessly.

I love that the audio file gets copied onto the top of the transcription, but I don't need an additional folder with the same audio files.

I'll double check the settings to see if I told it to do that.

Happy new year!


<img width="136" alt="Screenshot 2024-01-01 at 9 56 24 PM" src="https://github.com/vincentbavitz/obsidian-vox/assets/33947748/7e58cbf7-a498-4e7e-bb76-06e6bbd833a7">

**Comment by vincentbavitz** [comment]
Sorry @stevenjetton - that's definitely not meant to happen! 😆 I will try to reproduce this and bring out a fix today or tomorrow. I really really appreciate your patience!

**Comment by drjedd** [comment]
Hello and happy new year :)

I'm still getting the behaviour described in the first post of this thread.

I've tried uninstalling/reinstalling the plugin, clearing the queue and loading new files onto it.
But to no avail.

Thanks for your time :) All the best!

**Comment by kennygokh** [comment]
@vincentbavitz  Same issue. I am not getting the transcript file after waited for about an hour. Hope you can resolve it soon.

**Comment by ksdavidc** [comment]
also not working for me from start. Files get moved, but no transcription generated. I have tried different formats, e.g. webm which is default for recordings, and mp3. tried resetting the default folders in various ways. ften I will get the audio copied to the transcription folder, with the date prepended to teh date..but no transcription. No error messages that I could see. I probably reached the daily limit, so will have to troubleshoot at a later date. Hope to see it working someday. : - )

**Comment by MEltour** [comment]
still watching this plugin....I hope it gets fixed soon.

**Comment by vincentbavitz** [comment]
Thanks guys - this has been fixed now.

**Comment by Mahgozar** [comment]
Hi! thank you so much for such an amazing plugin, im facing the same issue unfortunately

**Comment by vincentbavitz** [comment]
Hey @Mahgozar - could you please give a screenshot of your VOX settings and your unprocessed folder?

I will have a look into this as soon as possible! :)

**Comment by arozwalak** [comment]
Hi @vincentbavitz , first thank you so much for the work. This plugin is missing piece for obsidian. Unfortunately at the moment transcription doesn't work. I've added screenshot of the issue I'm getting and plugin configuration. Hope it's easy to solve. Also I'm looking forward for self-hosted version. Do you have any release date in minde?

thanks!
<img width="380" alt="Screenshot 2024-12-10 at 20 14 21" src="https://github.com/user-attachments/assets/e5017c49-a947-4f85-ac15-9766a5211e06">
<img width="795" alt="Screenshot 2024-12-10 at 20 16 25" src="https://github.com/user-attachments/assets/c365917b-89af-4fa5-bae3-f264813732f8">
